#!/usr/bin/env python3
# generated by why0712 via ChatGPT 2026-06-17 03:00

import time
from datetime import datetime

import meshtastic.serial_interface
from pubsub import pub

# =====================================================
# CONFIG
# =====================================================

SERIAL_PORT = "/dev/ttyACM0"
LOG_FILE = "meshbot.log"

# =====================================================
# BOT
# =====================================================

class MeshBot:

    def __init__(self):

        self.last_activity = time.time()

        # Open logfile
        self.log_file = open(
            LOG_FILE,
            "a",
            buffering=1
        )

        self.log("SYSTEM", "Starting MeshBot...")

        self.iface = meshtastic.serial_interface.SerialInterface(
            devPath=SERIAL_PORT
        )

        self.my_id = self.iface.getMyUser().get(
            "id",
            ""
        )

        pub.subscribe(
            self.on_receive,
            "meshtastic.receive"
        )

        self.log(
            "SYSTEM",
            f"Connected as {self.my_id}"
        )

        self.log("SYSTEM", "Ready")

        self.log(
            "SYSTEM",
            f"========== BOT START {datetime.now()} =========="
        )

    # =====================================================
    # LOGGER
    # =====================================================

    def log(self, tag, message):

        ts = datetime.now().strftime(
            "%Y-%m-%d %H:%M:%S"
        )

        line = f"[{ts}] [{tag}] {message}"

        print(line)

        try:
            self.log_file.write(line + "\n")
            self.log_file.flush()
        except Exception:
            pass

    # =====================================================

    def send_reply(
        self,
        destination,
        message
    ):

        self.log(
            "TX",
            f"to={destination}"
        )

        self.log(
            "TX",
            message
        )

        try:

            self.iface.sendText(
                text=message,
                destinationId=destination
            )

            self.log(
                "TX",
                "success"
            )

        except Exception as e:

            self.log(
                "ERROR",
                str(e)
            )

    # =====================================================

    def get_uptime(self):

        try:

            with open("/proc/uptime") as f:
                uptime_seconds = float(
                    f.read().split()[0]
                )

            days = int(
                uptime_seconds // 86400
            )

            hours = int(
                (uptime_seconds % 86400) // 3600
            )

            minutes = int(
                (uptime_seconds % 3600) // 60
            )

            return (
                f"{days}d "
                f"{hours}h "
                f"{minutes}m"
            )

        except Exception as e:
            return str(e)

    # =====================================================

    def get_nodes(self):

        try:

            nodes = self.iface.nodes

            lines = [
                f"Known nodes: {len(nodes)}"
            ]

            count = 0

            for node_id, node in nodes.items():

                user = node.get(
                    "user",
                    {}
                )

                name = (
                    user.get("shortName")
                    or user.get("longName")
                    or node_id
                )

                lines.append(name)

                count += 1

                if count >= 10:
                    break

            return "\n".join(lines)

        except Exception as e:
            return f"Node error: {e}"

    # =====================================================

    def handle_command(
        self,
        command,
        sender,
        packet
    ):

        command = command.strip().lower()

        if command.startswith("!"):
            command = command[1:]

        self.log(
            "CMD",
            f"{sender}: {command}"
        )

        # -------------------------------------------------

        if command in ("admin", "commands", "list"):

            reply = (
                "Commands:\n"
                "ping\n"
                "time\n"
                "uptime\n"
                "nodes\n"
                "info\n"
                "admin\n"
                "commands\n"
                "list"
    )

        # -------------------------------------------------

        elif command == "time":

            reply = datetime.now().strftime(
                "%Y-%m-%d %H:%M:%S"
            )

        # -------------------------------------------------

        elif command == "uptime":

            reply = (
                f"Uptime: "
                f"{self.get_uptime()}"
            )

        # -------------------------------------------------

        elif command == "nodes":

            reply = self.get_nodes()

        # -------------------------------------------------

        elif command == "ping":

            rssi = packet.get(
                "rxRssi",
                "?"
            )

            snr = packet.get(
                "rxSnr",
                "?"
            )

            reply = (
                "PONG\n"
                f"RSSI: {rssi} dBm\n"
                f"SNR: {snr} dB"
            )

        # -------------------------------------------------

        elif command == "info":

            reply = (
                "MeshBot\n"
                "Meshtastic Interface\n"
                "Python Edition"
            )

        # -------------------------------------------------

        else:
            return

        self.send_reply(
            sender,
            reply
        )

    # =====================================================

    def on_receive(
        self,
        packet,
        interface
    ):

        try:

            self.log(
                "RAW",
                str(packet)
            )

            if "decoded" not in packet:
                return

            decoded = packet["decoded"]

            if (
                decoded.get("portnum")
                != "TEXT_MESSAGE_APP"
            ):
                return

            text = decoded.get(
                "text",
                ""
            ).strip()

            if not text:
                return

            sender = packet.get(
                "fromId"
            )

            self.log(
                "NODE",
                f"seen {sender}"
            )

            if sender == self.my_id:
                return

            self.log(
                "RX",
                f"{sender}: {text}"
            )

            self.last_activity = time.time()

            self.handle_command(
                text,
                sender,
                packet
            )

        except Exception as e:

            self.log(
                "ERROR",
                str(e)
            )

    # =====================================================

    def run(self):

        self.log(
            "SYSTEM",
            "loop running"
        )

        try:

            while True:
                time.sleep(1)

        except KeyboardInterrupt:

            self.log(
                "SYSTEM",
                "shutdown"
            )

            self.log(
                "SYSTEM",
                f"========== BOT STOP {datetime.now()} =========="
            )

            try:
                self.log_file.close()
            except Exception:
                pass

            try:
                self.iface.close()
            except Exception:
                pass

# =====================================================
# MAIN
# =====================================================

if __name__ == "__main__":

    MeshBot().run()
